check_csrf 사용 안함 옵션 추가
xpressengine/xe-core pull request #2075
Opened 2017-04-13 15:20 UTC by shlee322

XE에서 기본적으로 GET method를 제외한 모든 요청에 대해 checkCSRF를 통하여 referer 등을 체크하고 있습니다.
이는 외부와 연동되는 Restful API 등을 구현할 때 문제 요인으로 작용할 수 있습니다.
action에 check_csrf 옵션을 추가하여 부분적으로 특정 action에 checkCSRF를 호출하지 않도록 만들어 위의 문제 요인을 해결하였습니다.

```xml

<action name="procIamportNotify" type="controller" check_csrf="false"/>
```

2017-04-13 15:35 UTC, devxoul requested changes

2017-04-13 15:35 UTC, devxoul commented on modules/module/module.model.php
> +					$check_csrf = $action->attrs->check_csrf=='false'?'false':'true';
대소문자가 구분되어야 할 상황이 아니라면 lowercase로 검사하는 것에 대해서 어떻게 생각하시나요?

2017-04-13 15:39 UTC, shlee322 commented on modules/module/module.model.php
> +					$check_csrf = $action->attrs->check_csrf=='false'?'false':'true';
우선 기존 XE에서 사용하는 코드인 `$standalone = $action->attrs->standalone=='false'?'false':'true';` 와 동일한 형식으로 작성하였습니다.

2017-04-13 15:42 UTC, shlee322 commented on classes/module/ModuleHandler.class.php
> +		if($use_check_csrf && $_SERVER['REQUEST_METHOD'] !== 'GET' && Context::isInstalled() && $this->act !== 'procFileUpload' && !checkCSRF()) {
`$this->act !== 'procFileUpload'` 조건의 경우 향후 해당 PR이 머지 된다면 새로운 PR로 요청할 계획입니다.
(혹시 사용자가 동일 이름으로 정의해서 사용하고 있는 경우의 사이드 이펙트 방지)

2017-04-13 23:32 UTC, kijin commented on classes/module/ModuleHandler.class.php
> +		if($use_check_csrf && $_SERVER['REQUEST_METHOD'] !== 'GET' && Context::isInstalled() && $this->act !== 'procFileUpload' && !checkCSRF()) {
> (혹시 사용자가 동일 이름으로 정의해서 사용하고 있는 경우의 사이드 이펙트 방지)

proc**File**Upload 액션은 코어에 포함된 file 모듈이 선점하였으므로 다른 모듈에서 동일한 이름으로 사용한다면 그 모듈 잘못입니다.

물론 다른 방식으로 설정할 수 있게 된다면 굳이 여기서 예외처리할 필요가 없다는 데는 동의합니다.

2017-04-14 00:00 UTC, shlee322 commented on classes/module/ModuleHandler.class.php
> +		if($use_check_csrf && $_SERVER['REQUEST_METHOD'] !== 'GET' && Context::isInstalled() && $this->act !== 'procFileUpload' && !checkCSRF()) {
@kijin `$this->act !== 'procFileUpload'`와 동일한 처리를 위해 file 모듈의 `module.xml`의 procFileUpload action에 check_csrf 옵션을 추가하였습니다.

2017-05-15 07:49 UTC, merged